name:                exchangealgebra
version:             0.3.0.0
github:              "yakagika/ExchangeAlgebra"
license:             MIT
author:              "Kaya Akagi"
maintainer:          "kaya3728@gmail.com"
copyright:           "2019 Kaya Akagi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ExchangeAlgebra#readme>

dependencies:
- base
- text
- time
- containers
- lens
- numeric-prelude
- unicode-show
- non-negative
- bifunctors
- csv-parser
- array
- Chart
- Chart-cairo
- random
- mtl
- scientific

library:
  source-dirs: src


_exe-defs: &exe-defaults
  dependencies: exchangealgebra
  ghc-options: [-O2, -threaded, -rtsopts,-with-rtsopts=-N]


executables:
  calcex1:
    <<: *exe-defaults
    main:                calcEx1.hs
    source-dirs:         exsample

#  ssex1:
#    <<: *exe-defaults
#    main:                statespaceEx1.hs
#    source-dirs:         exsample

  ssex2:
    <<: *exe-defaults
    main:                statespaceEx2.hs
    source-dirs:         exsample

  ebex1:
    <<: *exe-defaults
    main:                elementaryBookkeepingEx1.hs
    source-dirs:         exsample

  ebex2:
    <<: *exe-defaults
    main:                elementaryBookkeepingEx2.hs
    source-dirs:         exsample

  ripple1:
    <<: *exe-defaults
    main:                rippleEffectEx1.hs
    source-dirs:         exsample

  maptest:
    <<: *exe-defaults
    main:                maptest.hs
    source-dirs:         exsample

tests:
  ExchangeAlgebra-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O1
    dependencies:
    - exchangealgebra

  ExchangeAlgebra-doctest:
    main: test/doctests.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O1
    dependencies:
    - exchangealgebra
    - doctest