name:                exchangealgebra
version:             0.4.0.0
github:              "yakagika/ExchangeAlgebra"
license:             MIT
author:              "Kaya Akagi"
maintainer:          "kaya3728@gmail.com"
copyright:           "2019 Kaya Akagi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ExchangeAlgebra#readme>

dependencies:
- base
- text
- time
- containers
- lens
- numeric-prelude
- unicode-show
- non-negative
- bifunctors
- csv-parser
- array
- Chart
- Chart-cairo
- random
- mtl
- scientific
- parallel
- deepseq
- vector
- async
- statistics
- hashable
- unordered-containers
- process

library:
  source-dirs: src


_exe-defs: &exe-defaults
  dependencies: exchangealgebra
  ghc-options: [-O2
               ,-threaded
               ,-rtsopts
               ,-with-rtsopts=-N
               ,-fwrite-ide-info]

executables:
  ebex1:
    <<: *exe-defaults
    main:                elementaryBookkeepingEx1.hs
    source-dirs:         exsample/basic

  ebex2:
    <<: *exe-defaults
    main:                elementaryBookkeepingEx2.hs
    source-dirs:         exsample/basic

  ebex3:
    <<: *exe-defaults
    main:                elementaryBookkeepingEx3.hs
    source-dirs:         exsample/basic

  ebex4:
    <<: *exe-defaults
    main:                elementaryBookkeepingEx4.hs
    source-dirs:         exsample/basic

  ebex5:
    <<: *exe-defaults
    main:                elementaryBookkeepingEx5.hs
    source-dirs:         exsample/basic

  sim1:
    <<: *exe-defaults
    main:                simulateEx1.hs
    source-dirs:         exsample/basic

  rippleWithStock:
    <<: *exe-defaults
    main:                rippleWithStock.hs
    source-dirs:         exsample/deterministic/ripple

  ripple:
    <<: *exe-defaults
    main:                ripple.hs
    source-dirs:         exsample/deterministic/ripple

  cge:
    <<: *exe-defaults
    main:                stdcge.hs
    source-dirs:         exsample/optimization/CGE

tests:
  ExchangeAlgebra-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O1
    dependencies:
    - exchangealgebra

  ExchangeAlgebra-doctest:
    main: test/doctests.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O1
    dependencies:
    - exchangealgebra
    - doctest