-- | Compile-time lock for the public names exported by
-- "ExchangeAlgebra.Accounting".
module Surface.Accounting
    ( AccountTitles
          ( Cash
          , Deposits
          , CurrentDeposits
          , Securities
          , InvestmentSecurities
          , InvestmentInAssociate
          , LongTermNationalBonds
          , ShortTermNationalBonds
          , Products
          , Machinery
          , Building
          , Vehicle
          , StockInvestment
          , EquipmentInvestment
          , LongTermLoansReceivable
          , AccountsReceivable
          , ShortTermLoansReceivable
          , ReserveDepositReceivable
          , Gold
          , GovernmentService
          , CapitalStock
          , RetainedEarnings
          , LongTermLoansPayable
          , ShortTermLoansPayable
          , LoansPayable
          , ReserveForDepreciation
          , DepositPayable
          , LongTermNationalBondsPayable
          , ShortTermNationalBondsPayable
          , ReserveDepositPayable
          , CentralBankNotePayable
          , Depreciation
          , AmortizationExpense
          , SalesCost
          , BusinessTrip
          , Commutation
          , UtilitiesExpense
          , RentExpense
          , AdvertisingExpense
          , DeliveryExpenses
          , SuppliesExpenses
          , MiscellaneousExpenses
          , WageExpenditure
          , InterestExpense
          , TaxesExpense
          , ConsumptionExpenditure
          , SubsidyExpense
          , CentralBankPaymentExpense
          , Purchases
          , NetIncome
          , ValueAdded
          , SubsidyIncome
          , NationalBondInterestEarned
          , DepositInterestEarned
          , GrossProfit
          , OrdinaryProfit
          , InterestEarned
          , ReceiptFee
          , RentalIncome
          , WageEarned
          , TaxesRevenue
          , CentralBankPaymentIncome
          , Sales
          , EquityInEarningsOfInvestee
          , NetLoss
          , PettyCash
          , NotesReceivable
          , ElectronicallyRecordedReceivable
          , CreditCardReceivable
          , NotesLoansReceivable
          , MerchandiseInventory
          , AdvancesPaid
          , PrepaidExpenses
          , AccruedRevenue
          , OtherReceivables
          , PaymentsOnBehalf
          , SuspensePayments
          , ConsumptionTaxPaid
          , PrepaidCorporateIncomeTaxes
          , Land
          , Fixtures
          , Patent
          , Trademark
          , Software
          , CashOverShort
          , AccountsPayable
          , NotesPayable
          , ElectronicallyRecordedObligations
          , NotesLoansPayable
          , BankOverdraft
          , AdvancesReceived
          , UnearnedRevenue
          , AccruedExpenses
          , OtherPayables
          , DepositsReceived
          , SuspenseReceipts
          , ConsumptionTaxReceived
          , AccruedConsumptionTax
          , AccruedCorporateIncomeTaxes
          , UnpaidDividends
          , AllowanceForDoubtfulAccounts
          , AccumulatedDepreciation
          , LegalRetainedEarnings
          , CumulativeTranslationAdjustment
          , ProvisionForDoubtfulAccounts
          , BadDebtLoss
          , LossOnSalesOfFixedAssets
          , LossOnSalesOfNotesReceivable
          , PaymentFees
          , MiscellaneousLoss
          , CorporateIncomeTaxes
          , CommunicationExpenses
          , GainOnSalesOfFixedAssets
          , RecoveryOfBadDebts
          , MiscellaneousIncome
          , ReversalOfAllowanceForDoubtfulAccounts
          , TimeDeposits
          , LoansReceivable
          , GiftCertificatesReceived
          , SecurityDepositsPaid
          , SuppliesOnHand
          , ContractAssets
          , IncomeTaxesRefundReceivable
          , WorkInProcess
          , DeferredTaxAssets
          , LeasedAssets
          , ToolsAndInstruments
          , ConstructionInProgress
          , Goodwill
          , SoftwareInProgress
          , LongTermPrepaidExpenses
          , DishonoredNotesReceivable
          , PrepaidPensionCost
          , NetDefinedBenefitAsset
          , DepositsInSpecialAccounts
          , Structures
          , LeaseholdRights
          , NonOperatingNotesReceivable
          , NonOperatingElectronicallyRecordedReceivable
          , RefundLiabilities
          , NonOperatingNotesPayable
          , NonOperatingElectronicallyRecordedObligations
          , BonusesPayable
          , AllowanceForRepairs
          , AllowanceForProductWarranties
          , AllowanceForBonuses
          , DeferredTaxLiabilities
          , LeaseObligations
          , GuaranteeDepositsReceived
          , AllowanceForRetirementBenefits
          , LongTermOtherPayables
          , NetDefinedBenefitLiability
          , StockSubscriptionDeposits
          , LegalCapitalSurplus
          , OtherCapitalSurplus
          , DividendEqualizationReserve
          , RepairFundReserve
          , ConstructionFundReserve
          , GeneralReserve
          , ValuationDifferenceOnOtherSecurities
          , NonControllingInterests
          , CapitalSurplus
          , EarnedSurplus
          , ServiceRevenue
          , OperatingRevenue
          , GainOnSalesOfSecurities
          , GainOnValuationOfSecurities
          , DividendsReceived
          , InterestOnSecurities
          , GainOnSalesOfInvestmentSecurities
          , InsuranceGain
          , GainOnBargainPurchase
          , ReversalOfAllowanceForRepairs
          , ReversalOfAllowanceForProductWarranties
          , GainOnDonationOfFixedAssets
          , GainOnNationalSubsidies
          , GainOnConstructionGrants
          , LandRentReceived
          , SalesRebates
          , CostOfServices
          , OperatingExpenses
          , InventoryShrinkageLoss
          , LossOnValuationOfMerchandise
          , Bonuses
          , RetirementBenefitExpenses
          , ProvisionForRepairs
          , ProvisionForBonuses
          , ProvisionForProductWarranties
          , ResearchAndDevelopmentExpenses
          , AmortizationOfGoodwill
          , AmortizationOfSoftware
          , AmortizationOfPatents
          , LeaseExpenses
          , IncorporationExpenses
          , StockIssuanceCosts
          , BusinessCommencementExpenses
          , DevelopmentExpenses
          , LossOnSalesOfElectronicallyRecordedReceivables
          , LossOnSalesOfReceivables
          , LossOnSalesOfSecurities
          , LossOnValuationOfSecurities
          , LossOnSalesOfInvestmentSecurities
          , LossOnFire
          , LossOnRetirementOfFixedAssets
          , LossOnReductionOfFixedAssets
          , AdditionalIncomeTaxesForPriorPeriods
          , RefundOfIncomeTaxes
          , PurchaseRebates
          , WelfareExpenses
          , MaintenanceExpenses
          , StatutoryWelfareExpenses
          , LandRentPaid
          , InsuranceExpense
          , RepairsExpense
          , StorageExpenses
          , MembershipFees
          , IncomeSummary
          , SuspenseAccount
          , ForeignExchangeGains
          , ForeignExchangeLosses
          , ContraAccountForGuaranteeObligations
          , GuaranteeObligations
          , IncomeTaxesAdjustment
          , BranchCurrentAccount
          , HeadOfficeCurrentAccount
          , NetIncomeAttributableToNCI
          , NetLossAttributableToNCI
          , TradingSecurities
          , HeldToMaturityBonds
          , SubsidiaryStocks
          , AffiliateStocks
          , AvailableForSaleSecurities
          , ConsumptionTaxRefundReceivable
          , PropertyTaxPayable
          , DepositsReceivedFromOfficers
          , EntertainmentExpenses
          , MeetingExpenses
          , NewspaperBooksExpenses
          , RawMaterials
          , GoodsInTransit
          , AccountTitle
          )
    , AccountDivision
          ( Assets
          , Equity
          , Liability
          , Cost
          , Revenue
          )
    , Side (Credit, Debit, Side)
    , FixedCurrent (Fixed, Current, Other)
    , PIMO (PS, IN, MS, OUT)
    , ExBaseClass
          ( getAccountTitle
          , setAccountTitle
          , (.~)
          , whatDiv
          , isContra
          , whatPIMO
          , whichSide
          , fixedCurrent
          )
    , AccountBase ((<=>))
    , switchSide
    , defaultSide
    , classifyAccountDivision
    , pimoFromDivision
    , pimoFlip
    , Exchange
          ( decR
          , decL
          , decP
          , decM
          , balance
          , diffRL
          )
    , projCredit
    , projDebit
    , projByAccountTitle
    , projCurrentAssets
    , projFixedAssets
    , projDeferredAssets
    , projCurrentLiability
    , projFixedLiability
    , projCapitalStock
    , projContraAssets
    , projContra
    , TransTable
    , TransTableParts
    , Size
    , isNullTable
    , table
    , (.->)
    , (|%)
    , createTransfer
    , transfer
    ) where

import           ExchangeAlgebra.Accounting
                     ( AccountTitles
                           ( Cash
                           , Deposits
                           , CurrentDeposits
                           , Securities
                           , InvestmentSecurities
                           , InvestmentInAssociate
                           , LongTermNationalBonds
                           , ShortTermNationalBonds
                           , Products
                           , Machinery
                           , Building
                           , Vehicle
                           , StockInvestment
                           , EquipmentInvestment
                           , LongTermLoansReceivable
                           , AccountsReceivable
                           , ShortTermLoansReceivable
                           , ReserveDepositReceivable
                           , Gold
                           , GovernmentService
                           , CapitalStock
                           , RetainedEarnings
                           , LongTermLoansPayable
                           , ShortTermLoansPayable
                           , LoansPayable
                           , ReserveForDepreciation
                           , DepositPayable
                           , LongTermNationalBondsPayable
                           , ShortTermNationalBondsPayable
                           , ReserveDepositPayable
                           , CentralBankNotePayable
                           , Depreciation
                           , AmortizationExpense
                           , SalesCost
                           , BusinessTrip
                           , Commutation
                           , UtilitiesExpense
                           , RentExpense
                           , AdvertisingExpense
                           , DeliveryExpenses
                           , SuppliesExpenses
                           , MiscellaneousExpenses
                           , WageExpenditure
                           , InterestExpense
                           , TaxesExpense
                           , ConsumptionExpenditure
                           , SubsidyExpense
                           , CentralBankPaymentExpense
                           , Purchases
                           , NetIncome
                           , ValueAdded
                           , SubsidyIncome
                           , NationalBondInterestEarned
                           , DepositInterestEarned
                           , GrossProfit
                           , OrdinaryProfit
                           , InterestEarned
                           , ReceiptFee
                           , RentalIncome
                           , WageEarned
                           , TaxesRevenue
                           , CentralBankPaymentIncome
                           , Sales
                           , EquityInEarningsOfInvestee
                           , NetLoss
                           , PettyCash
                           , NotesReceivable
                           , ElectronicallyRecordedReceivable
                           , CreditCardReceivable
                           , NotesLoansReceivable
                           , MerchandiseInventory
                           , AdvancesPaid
                           , PrepaidExpenses
                           , AccruedRevenue
                           , OtherReceivables
                           , PaymentsOnBehalf
                           , SuspensePayments
                           , ConsumptionTaxPaid
                           , PrepaidCorporateIncomeTaxes
                           , Land
                           , Fixtures
                           , Patent
                           , Trademark
                           , Software
                           , CashOverShort
                           , AccountsPayable
                           , NotesPayable
                           , ElectronicallyRecordedObligations
                           , NotesLoansPayable
                           , BankOverdraft
                           , AdvancesReceived
                           , UnearnedRevenue
                           , AccruedExpenses
                           , OtherPayables
                           , DepositsReceived
                           , SuspenseReceipts
                           , ConsumptionTaxReceived
                           , AccruedConsumptionTax
                           , AccruedCorporateIncomeTaxes
                           , UnpaidDividends
                           , AllowanceForDoubtfulAccounts
                           , AccumulatedDepreciation
                           , LegalRetainedEarnings
                           , CumulativeTranslationAdjustment
                           , ProvisionForDoubtfulAccounts
                           , BadDebtLoss
                           , LossOnSalesOfFixedAssets
                           , LossOnSalesOfNotesReceivable
                           , PaymentFees
                           , MiscellaneousLoss
                           , CorporateIncomeTaxes
                           , CommunicationExpenses
                           , GainOnSalesOfFixedAssets
                           , RecoveryOfBadDebts
                           , MiscellaneousIncome
                           , ReversalOfAllowanceForDoubtfulAccounts
                           , TimeDeposits
                           , LoansReceivable
                           , GiftCertificatesReceived
                           , SecurityDepositsPaid
                           , SuppliesOnHand
                           , ContractAssets
                           , IncomeTaxesRefundReceivable
                           , WorkInProcess
                           , DeferredTaxAssets
                           , LeasedAssets
                           , ToolsAndInstruments
                           , ConstructionInProgress
                           , Goodwill
                           , SoftwareInProgress
                           , LongTermPrepaidExpenses
                           , DishonoredNotesReceivable
                           , PrepaidPensionCost
                           , NetDefinedBenefitAsset
                           , DepositsInSpecialAccounts
                           , Structures
                           , LeaseholdRights
                           , NonOperatingNotesReceivable
                           , NonOperatingElectronicallyRecordedReceivable
                           , RefundLiabilities
                           , NonOperatingNotesPayable
                           , NonOperatingElectronicallyRecordedObligations
                           , BonusesPayable
                           , AllowanceForRepairs
                           , AllowanceForProductWarranties
                           , AllowanceForBonuses
                           , DeferredTaxLiabilities
                           , LeaseObligations
                           , GuaranteeDepositsReceived
                           , AllowanceForRetirementBenefits
                           , LongTermOtherPayables
                           , NetDefinedBenefitLiability
                           , StockSubscriptionDeposits
                           , LegalCapitalSurplus
                           , OtherCapitalSurplus
                           , DividendEqualizationReserve
                           , RepairFundReserve
                           , ConstructionFundReserve
                           , GeneralReserve
                           , ValuationDifferenceOnOtherSecurities
                           , NonControllingInterests
                           , CapitalSurplus
                           , EarnedSurplus
                           , ServiceRevenue
                           , OperatingRevenue
                           , GainOnSalesOfSecurities
                           , GainOnValuationOfSecurities
                           , DividendsReceived
                           , InterestOnSecurities
                           , GainOnSalesOfInvestmentSecurities
                           , InsuranceGain
                           , GainOnBargainPurchase
                           , ReversalOfAllowanceForRepairs
                           , ReversalOfAllowanceForProductWarranties
                           , GainOnDonationOfFixedAssets
                           , GainOnNationalSubsidies
                           , GainOnConstructionGrants
                           , LandRentReceived
                           , SalesRebates
                           , CostOfServices
                           , OperatingExpenses
                           , InventoryShrinkageLoss
                           , LossOnValuationOfMerchandise
                           , Bonuses
                           , RetirementBenefitExpenses
                           , ProvisionForRepairs
                           , ProvisionForBonuses
                           , ProvisionForProductWarranties
                           , ResearchAndDevelopmentExpenses
                           , AmortizationOfGoodwill
                           , AmortizationOfSoftware
                           , AmortizationOfPatents
                           , LeaseExpenses
                           , IncorporationExpenses
                           , StockIssuanceCosts
                           , BusinessCommencementExpenses
                           , DevelopmentExpenses
                           , LossOnSalesOfElectronicallyRecordedReceivables
                           , LossOnSalesOfReceivables
                           , LossOnSalesOfSecurities
                           , LossOnValuationOfSecurities
                           , LossOnSalesOfInvestmentSecurities
                           , LossOnFire
                           , LossOnRetirementOfFixedAssets
                           , LossOnReductionOfFixedAssets
                           , AdditionalIncomeTaxesForPriorPeriods
                           , RefundOfIncomeTaxes
                           , PurchaseRebates
                           , WelfareExpenses
                           , MaintenanceExpenses
                           , StatutoryWelfareExpenses
                           , LandRentPaid
                           , InsuranceExpense
                           , RepairsExpense
                           , StorageExpenses
                           , MembershipFees
                           , IncomeSummary
                           , SuspenseAccount
                           , ForeignExchangeGains
                           , ForeignExchangeLosses
                           , ContraAccountForGuaranteeObligations
                           , GuaranteeObligations
                           , IncomeTaxesAdjustment
                           , BranchCurrentAccount
                           , HeadOfficeCurrentAccount
                           , NetIncomeAttributableToNCI
                           , NetLossAttributableToNCI
                           , TradingSecurities
                           , HeldToMaturityBonds
                           , SubsidiaryStocks
                           , AffiliateStocks
                           , AvailableForSaleSecurities
                           , ConsumptionTaxRefundReceivable
                           , PropertyTaxPayable
                           , DepositsReceivedFromOfficers
                           , EntertainmentExpenses
                           , MeetingExpenses
                           , NewspaperBooksExpenses
                           , RawMaterials
                           , GoodsInTransit
                           , AccountTitle
                           )
                     , AccountDivision
                           ( Assets
                           , Equity
                           , Liability
                           , Cost
                           , Revenue
                           )
                     , Side (Credit, Debit, Side)
                     , FixedCurrent (Fixed, Current, Other)
                     , PIMO (PS, IN, MS, OUT)
                     , ExBaseClass
                           ( getAccountTitle
                           , setAccountTitle
                           , (.~)
                           , whatDiv
                           , isContra
                           , whatPIMO
                           , whichSide
                           , fixedCurrent
                           )
                     , AccountBase ((<=>))
                     , switchSide
                     , defaultSide
                     , classifyAccountDivision
                     , pimoFromDivision
                     , pimoFlip
                     , Exchange
                           ( decR
                           , decL
                           , decP
                           , decM
                           , balance
                           , diffRL
                           )
                     , projCredit
                     , projDebit
                     , projByAccountTitle
                     , projCurrentAssets
                     , projFixedAssets
                     , projDeferredAssets
                     , projCurrentLiability
                     , projFixedLiability
                     , projCapitalStock
                     , projContraAssets
                     , projContra
                     , TransTable
                     , TransTableParts
                     , Size
                     , isNullTable
                     , table
                     , (.->)
                     , (|%)
                     , createTransfer
                     , transfer
                     )
