{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-deprecations #-}

-- GENERATED by tools/gen-assist-descriptions.py — do not edit

module ExchangeAlgebra.Assist.Descriptions
    ( accountDescriptions
    ) where

import Data.Text (Text)

import ExchangeAlgebra.Algebra.Base (AccountTitles(..))

accountDescriptions :: [(AccountTitles, Text, Text, Text)]
accountDescriptions =
  [
    ( Cash
    , "Cash"
    , "現金"
    , "Asset: Cash (現金)"
    )
  , ( Deposits
    , "Savings deposits"
    , "普通預金"
    , "Asset: Savings deposits (普通預金)"
    )
  , ( CurrentDeposits
    , "Current deposits"
    , "当座預金"
    , "Asset: Current deposits (当座預金)"
    )
  , ( Securities
    , "Securities"
    , "有価証券"
    , "Asset: Securities (有価証券)"
    )
  , ( InvestmentSecurities
    , "Investment securities"
    , "投資有価証券"
    , "Asset: Investment securities (投資有価証券)"
    )
  , ( InvestmentInAssociate
    , "Investment in associate"
    , "関係会社株式"
    , "Asset: Investment in associate (関係会社株式). Carrying amount under the equity method (持分法適用投資勘定)."
    )
  , ( LongTermNationalBonds
    , "Long-term national bonds"
    , "長期国債"
    , "Asset: Long-term national bonds (長期国債)"
    )
  , ( ShortTermNationalBonds
    , "Short-term national bonds"
    , "短期国債"
    , "Asset: Short-term national bonds (短期国債)"
    )
  , ( Products
    , "Products"
    , "商品"
    , "Asset: Products (商品)。分記法用。3 分法 (仕入\\/売上\\/繰越商品) では 'MerchandiseInventory' を使う"
    )
  , ( Machinery
    , "Machinery and equipment"
    , "機械装置"
    , "Asset: Machinery and equipment (機械装置)"
    )
  , ( Building
    , "Real estate"
    , "建物"
    , "Asset: Real estate (建物)"
    )
  , ( Vehicle
    , "Vehicles"
    , "車両運搬具"
    , "Asset: Vehicles (車両運搬具)"
    )
  , ( StockInvestment
    , "Stock investment"
    , "株式投資"
    , "Asset: Stock investment (株式投資)"
    )
  , ( EquipmentInvestment
    , "Equipment investment"
    , "設備投資"
    , "Asset: Equipment investment (設備投資)"
    )
  , ( LongTermLoansReceivable
    , "Long-term loans receivable"
    , "長期貸付金"
    , "Asset: Long-term loans receivable (長期貸付金)"
    )
  , ( AccountsReceivable
    , "Accounts receivable"
    , "売掛金"
    , "Asset: Accounts receivable (売掛金)"
    )
  , ( ShortTermLoansReceivable
    , "Short-term loans receivable"
    , "短期貸付金"
    , "Asset: Short-term loans receivable (短期貸付金)"
    )
  , ( ReserveDepositReceivable
    , "Reserve deposits, asset side"
    , "準備預金, 資産側 — 市中銀行が中央銀行に置く準備預金。SNA\\/マクロ系"
    , "Asset: Reserve deposits, asset side (準備預金, 資産側 — 市中銀行が中央銀行に置く準備預金。SNA\\/マクロ系)"
    )
  , ( Gold
    , "Gold"
    , "金"
    , "Asset: Gold (金)"
    )
  , ( GovernmentService
    , "Government service"
    , "政府サービス。SNA\\/マクロ系"
    , "Asset: Government service (政府サービス。SNA\\/マクロ系)"
    )
  , ( CapitalStock
    , "Capital stock"
    , "資本金"
    , "Equity: Capital stock (資本金)"
    )
  , ( RetainedEarnings
    , "Retained earnings"
    , "繰越利益剰余金"
    , "Equity: Retained earnings (繰越利益剰余金)"
    )
  , ( LongTermLoansPayable
    , "Long-term loans payable"
    , "長期借入金"
    , "Liability: Long-term loans payable (長期借入金)"
    )
  , ( ShortTermLoansPayable
    , "Short-term loans payable"
    , "短期借入金"
    , "Liability: Short-term loans payable (短期借入金)"
    )
  , ( LoansPayable
    , "Loans payable"
    , "借入金"
    , "Liability: Loans payable (借入金)"
    )
  , ( ReserveForDepreciation
    , "Reserve for depreciation"
    , "減価償却引当金 — SNA\\/マクロ系の旧称。簿記の間接法には 'AccumulatedDepreciation' (減価償却累計額"
    , "Liability: Reserve for depreciation (減価償却引当金 — SNA\\/マクロ系の旧称。簿記の間接法には 'AccumulatedDepreciation' (減価償却累計額) を使う)"
    )
  , ( DepositPayable
    , "Deposits accepted"
    , "受入預金 — 銀行側の負債としての預金。SNA\\/マクロ系。従業員等からの預り金は 'DepositsReceived'"
    , "Liability: Deposits accepted (受入預金 — 銀行側の負債としての預金。SNA\\/マクロ系。従業員等からの預り金は 'DepositsReceived')"
    )
  , ( LongTermNationalBondsPayable
    , "Long-term national bonds payable"
    , "長期国債, 発行側"
    , "Liability: Long-term national bonds payable (長期国債, 発行側)"
    )
  , ( ShortTermNationalBondsPayable
    , "Short-term national bonds payable"
    , "短期国債, 発行側"
    , "Liability: Short-term national bonds payable (短期国債, 発行側)"
    )
  , ( ReserveDepositPayable
    , "Reserve deposits, liability side"
    , "準備預金, 負債側 — 中央銀行が受け入れる準備預金。SNA\\/マクロ系"
    , "Liability: Reserve deposits, liability side (準備預金, 負債側 — 中央銀行が受け入れる準備預金。SNA\\/マクロ系)。※簿記の買掛金は 'AccountsPayable' を使うこと (旧 examples が本科目を買掛金の代用にしていた経緯あり)"
    )
  , ( CentralBankNotePayable
    , "Central bank notes"
    , "発行銀行券。SNA\\/マクロ系"
    , "Liability: Central bank notes (発行銀行券。SNA\\/マクロ系)"
    )
  , ( Depreciation
    , "Depreciation"
    , "減価償却費"
    , "Expense: Depreciation (減価償却費)"
    )
  , ( AmortizationExpense
    , "Amortization expense for intangibles"
    , "無形固定資産償却費 — 特許権・商標権・ソフトウェア等の無形資産の償却費。有形の 'Depreciation' (減価償却費"
    , "Expense: Amortization expense for intangibles (無形固定資産償却費 — 特許権・商標権・ソフトウェア等の無形資産の償却費。有形の 'Depreciation' (減価償却費) と区別される)"
    )
  , ( SalesCost
    , "Cost of sales"
    , "売上原価"
    , "Expense: Cost of sales (売上原価)"
    )
  , ( BusinessTrip
    , "Travel and transportation"
    , "旅費交通費"
    , "Expense: Travel and transportation (旅費交通費)"
    )
  , ( Commutation
    , "Communication"
    , "通信費 — 旧称。新規コードでは 'CommunicationExpenses' を使う"
    , "Expense: Communication (通信費 — 旧称。新規コードでは 'CommunicationExpenses' を使う)"
    )
  , ( UtilitiesExpense
    , "Utilities"
    , "水道光熱費"
    , "Expense: Utilities (水道光熱費)"
    )
  , ( RentExpense
    , "Rent"
    , "支払家賃"
    , "Expense: Rent (支払家賃)"
    )
  , ( AdvertisingExpense
    , "Advertising"
    , "広告宣伝費"
    , "Expense: Advertising (広告宣伝費)"
    )
  , ( DeliveryExpenses
    , "Delivery"
    , "発送費"
    , "Expense: Delivery (発送費)"
    )
  , ( SuppliesExpenses
    , "Supplies"
    , "消耗品費"
    , "Expense: Supplies (消耗品費)"
    )
  , ( MiscellaneousExpenses
    , "Miscellaneous"
    , "雑費"
    , "Expense: Miscellaneous (雑費)"
    )
  , ( WageExpenditure
    , "Wages"
    , "給料"
    , "Expense: Wages (給料)"
    )
  , ( InterestExpense
    , "Interest expense"
    , "支払利息"
    , "Expense: Interest expense (支払利息)"
    )
  , ( TaxesExpense
    , "Taxes"
    , "租税公課"
    , "Expense: Taxes (租税公課)"
    )
  , ( ConsumptionExpenditure
    , "Consumption expenditure"
    , "消費支出。SNA\\/マクロ系"
    , "Expense: Consumption expenditure (消費支出。SNA\\/マクロ系)"
    )
  , ( SubsidyExpense
    , "Subsidy expenditure"
    , "補助金支出。SNA\\/マクロ系"
    , "Expense: Subsidy expenditure (補助金支出。SNA\\/マクロ系)"
    )
  , ( CentralBankPaymentExpense
    , "Central bank payment to treasury"
    , "国庫納付金支出。SNA\\/マクロ系"
    , "Expense: Central bank payment to treasury (国庫納付金支出。SNA\\/マクロ系)"
    )
  , ( Purchases
    , "Purchases"
    , "仕入"
    , "Expense: Purchases (仕入)"
    )
  , ( NetIncome
    , "Net income"
    , "当期純利益 — 決算振替用。借方側に立つため Expense 区分"
    , "Expense: Net income (当期純利益 — 決算振替用。借方側に立つため Expense 区分)"
    )
  , ( ValueAdded
    , "Value added"
    , "付加価値。SNA\\/マクロ系"
    , "Revenue: Value added (付加価値。SNA\\/マクロ系)"
    )
  , ( SubsidyIncome
    , "Subsidy income"
    , "補助金収入。SNA\\/マクロ系"
    , "Revenue: Subsidy income (補助金収入。SNA\\/マクロ系)"
    )
  , ( NationalBondInterestEarned
    , "National bond interest earned"
    , "国債利息収入"
    , "Revenue: National bond interest earned (国債利息収入)"
    )
  , ( DepositInterestEarned
    , "Deposit interest earned"
    , "預金利息収入"
    , "Revenue: Deposit interest earned (預金利息収入)"
    )
  , ( GrossProfit
    , "Gross profit"
    , "売上総利益 — 決算振替用"
    , "Revenue: Gross profit (売上総利益 — 決算振替用)"
    )
  , ( OrdinaryProfit
    , "Ordinary profit"
    , "経常利益 — 決算振替用"
    , "Revenue: Ordinary profit (経常利益 — 決算振替用)"
    )
  , ( InterestEarned
    , "Interest earned"
    , "受取利息"
    , "Revenue: Interest earned (受取利息)"
    )
  , ( ReceiptFee
    , "Receipt fee"
    , "受取手数料。支払側は 'PaymentFees'"
    , "Revenue: Receipt fee (受取手数料。支払側は 'PaymentFees')"
    )
  , ( RentalIncome
    , "Rental income"
    , "受取家賃"
    , "Revenue: Rental income (受取家賃)"
    )
  , ( WageEarned
    , "Wage income"
    , "賃金収入。SNA\\/マクロ系"
    , "Revenue: Wage income (賃金収入。SNA\\/マクロ系)"
    )
  , ( TaxesRevenue
    , "Tax revenue"
    , "租税収入。SNA\\/マクロ系"
    , "Revenue: Tax revenue (租税収入。SNA\\/マクロ系)"
    )
  , ( CentralBankPaymentIncome
    , "Central bank payment to treasury"
    , "国庫納付金収入。SNA\\/マクロ系"
    , "Revenue: Central bank payment to treasury (国庫納付金収入。SNA\\/マクロ系)"
    )
  , ( Sales
    , "Sales"
    , "売上"
    , "Revenue: Sales (売上)"
    )
  , ( EquityInEarningsOfInvestee
    , "Equity in earnings of investee"
    , "持分法による投資利益"
    , "Revenue: Equity in earnings of investee (持分法による投資利益). Recognised under the equity method."
    )
  , ( NetLoss
    , "Net loss"
    , "当期純損失 — 決算振替用。貸方側に立つため Revenue 区分"
    , "Revenue: Net loss (当期純損失 — 決算振替用。貸方側に立つため Revenue 区分)"
    )
  , ( PettyCash
    , "Petty cash"
    , "小口現金"
    , "Asset: Petty cash (小口現金)"
    )
  , ( NotesReceivable
    , "Notes receivable"
    , "受取手形"
    , "Asset: Notes receivable (受取手形)"
    )
  , ( ElectronicallyRecordedReceivable
    , "Electronically recorded monetary claims"
    , "電子記録債権"
    , "Asset: Electronically recorded monetary claims (電子記録債権)"
    )
  , ( CreditCardReceivable
    , "Credit card receivable"
    , "クレジット売掛金"
    , "Asset: Credit card receivable (クレジット売掛金)"
    )
  , ( NotesLoansReceivable
    , "Loans receivable on notes"
    , "手形貸付金"
    , "Asset: Loans receivable on notes (手形貸付金)"
    )
  , ( MerchandiseInventory
    , "Merchandise inventory"
    , "繰越商品"
    , "Asset: Merchandise inventory (繰越商品). Use under the periodic/3-account method (3 分法: Purchases\\/Sales\\/MerchandiseInventory). For the perpetual\\/specific-identification method (分記法) use 'Products' instead."
    )
  , ( AdvancesPaid
    , "Advances paid"
    , "前払金"
    , "Asset: Advances paid (前払金)"
    )
  , ( PrepaidExpenses
    , "Prepaid expenses"
    , "前払費用"
    , "Asset: Prepaid expenses (前払費用), deferral accrual account (経過勘定)"
    )
  , ( AccruedRevenue
    , "Accrued revenue"
    , "未収収益"
    , "Asset: Accrued revenue (未収収益), deferral accrual account (経過勘定)"
    )
  , ( OtherReceivables
    , "Other receivables"
    , "未収入金"
    , "Asset: Other receivables (未収入金)"
    )
  , ( PaymentsOnBehalf
    , "Payments made on behalf"
    , "立替金"
    , "Asset: Payments made on behalf (立替金)"
    )
  , ( SuspensePayments
    , "Suspense payments"
    , "仮払金"
    , "Asset: Suspense payments (仮払金)"
    )
  , ( ConsumptionTaxPaid
    , "Consumption tax paid"
    , "仮払消費税"
    , "Asset: Consumption tax paid (仮払消費税)"
    )
  , ( PrepaidCorporateIncomeTaxes
    , "Prepaid corporate income taxes"
    , "仮払法人税等"
    , "Asset: Prepaid corporate income taxes (仮払法人税等)"
    )
  , ( Land
    , "Land"
    , "土地"
    , "Asset: Land (土地)"
    )
  , ( Fixtures
    , "Fixtures and equipment"
    , "備品"
    , "Asset: Fixtures and equipment (備品)"
    )
  , ( Patent
    , "Patent"
    , "特許権"
    , "Asset: Patent (特許権)"
    )
  , ( Trademark
    , "Trademark"
    , "商標権"
    , "Asset: Trademark (商標権)"
    )
  , ( Software
    , "Software"
    , "ソフトウェア"
    , "Asset: Software (ソフトウェア)"
    )
  , ( CashOverShort
    , "Cash over and short"
    , "現金過不足"
    , "Asset: Cash over and short (現金過不足), a temporary/suspense account cleared at closing to MiscellaneousIncome\\/MiscellaneousLoss"
    )
  , ( AccountsPayable
    , "Accounts payable"
    , "買掛金"
    , "Liability: Accounts payable (買掛金)"
    )
  , ( NotesPayable
    , "Notes payable"
    , "支払手形"
    , "Liability: Notes payable (支払手形)"
    )
  , ( ElectronicallyRecordedObligations
    , "Electronically recorded monetary obligations"
    , "電子記録債務"
    , "Liability: Electronically recorded monetary obligations (電子記録債務)"
    )
  , ( NotesLoansPayable
    , "Loans payable on notes"
    , "手形借入金"
    , "Liability: Loans payable on notes (手形借入金)"
    )
  , ( BankOverdraft
    , "Bank overdraft"
    , "当座借越"
    , "Liability: Bank overdraft (当座借越)"
    )
  , ( AdvancesReceived
    , "Advances received"
    , "前受金"
    , "Liability: Advances received (前受金)"
    )
  , ( UnearnedRevenue
    , "Unearned revenue"
    , "前受収益"
    , "Liability: Unearned revenue (前受収益), deferral accrual account (経過勘定)"
    )
  , ( AccruedExpenses
    , "Accrued expenses"
    , "未払費用"
    , "Liability: Accrued expenses (未払費用), deferral accrual account (経過勘定)"
    )
  , ( OtherPayables
    , "Other payables"
    , "未払金"
    , "Liability: Other payables (未払金)"
    )
  , ( DepositsReceived
    , "Deposits received"
    , "預り金"
    , "Liability: Deposits received (預り金)"
    )
  , ( SuspenseReceipts
    , "Suspense receipts"
    , "仮受金"
    , "Liability: Suspense receipts (仮受金)"
    )
  , ( ConsumptionTaxReceived
    , "Consumption tax received"
    , "仮受消費税"
    , "Liability: Consumption tax received (仮受消費税)"
    )
  , ( AccruedConsumptionTax
    , "Accrued (unpaid) consumption tax"
    , "未払消費税"
    , "Liability: Accrued (unpaid) consumption tax (未払消費税)"
    )
  , ( AccruedCorporateIncomeTaxes
    , "Accrued (unpaid) corporate income taxes"
    , "未払法人税等"
    , "Liability: Accrued (unpaid) corporate income taxes (未払法人税等)"
    )
  , ( UnpaidDividends
    , "Unpaid dividends"
    , "未払配当金"
    , "Liability: Unpaid dividends (未払配当金)"
    )
  , ( AllowanceForDoubtfulAccounts
    , "Allowance for doubtful accounts"
    , "貸倒引当金"
    , "Liability: Allowance for doubtful accounts (貸倒引当金). Modeled as an independent credit-balance valuation account (評価勘定) classified under Liability: this keeps values non-negative and the Hat\\/Not structure intact, deferring the B\\/S contra-asset (deduction) presentation to the Write side, rather than adding a new AccountDivision (over-engineered at the 3-級 level)."
    )
  , ( AccumulatedDepreciation
    , "Accumulated depreciation"
    , "減価償却累計額"
    , "Liability: Accumulated depreciation (減価償却累計額), valuation account (評価勘定) under the indirect method (間接法). Classified under Liability for the same reason as 'AllowanceForDoubtfulAccounts'. This is the canonical bookkeeping account for accumulated depreciation; the existing 'ReserveForDepreciation' is retained as the legacy SNA\\/macro-accounting name."
    )
  , ( LegalRetainedEarnings
    , "Legal (appropriated) retained earnings reserve"
    , "利益準備金"
    , "Equity: Legal (appropriated) retained earnings reserve (利益準備金)"
    )
  , ( CumulativeTranslationAdjustment
    , "Cumulative translation adjustment"
    , "為替換算調整勘定; 在外子会社等の外貨建財務諸表の換算差額を計上する OCI/資本の部の項目"
    , "Equity: Cumulative translation adjustment (為替換算調整勘定; 在外子会社等の外貨建財務諸表の換算差額を計上する OCI/資本の部の項目)"
    )
  , ( ProvisionForDoubtfulAccounts
    , "Provision for doubtful accounts"
    , "貸倒引当金繰入"
    , "Cost: Provision for doubtful accounts (貸倒引当金繰入)"
    )
  , ( BadDebtLoss
    , "Bad debt loss"
    , "貸倒損失"
    , "Cost: Bad debt loss (貸倒損失)"
    )
  , ( LossOnSalesOfFixedAssets
    , "Loss on sales of fixed assets"
    , "固定資産売却損"
    , "Cost: Loss on sales of fixed assets (固定資産売却損)"
    )
  , ( LossOnSalesOfNotesReceivable
    , "Loss on sales of notes receivable"
    , "手形売却損"
    , "Cost: Loss on sales of notes receivable (手形売却損)"
    )
  , ( PaymentFees
    , "Payment fees / fees paid"
    , "支払手数料"
    , "Cost: Payment fees / fees paid (支払手数料), the debit counterpart of 'ReceiptFee'"
    )
  , ( MiscellaneousLoss
    , "Miscellaneous loss"
    , "雑損"
    , "Cost: Miscellaneous loss (雑損)"
    )
  , ( CorporateIncomeTaxes
    , "Corporate income taxes"
    , "法人税等"
    , "Cost: Corporate income taxes (法人税等)"
    )
  , ( CommunicationExpenses
    , "Communication expenses"
    , "通信費"
    , "Cost: Communication expenses (通信費). Explicitly named counterpart of the legacy 'Commutation' (also \"Communication\"); 'Commutation' is retained for backward compatibility."
    )
  , ( GainOnSalesOfFixedAssets
    , "Gain on sales of fixed assets"
    , "固定資産売却益"
    , "Revenue: Gain on sales of fixed assets (固定資産売却益)"
    )
  , ( RecoveryOfBadDebts
    , "Recovery of bad debts written off"
    , "償却債権取立益"
    , "Revenue: Recovery of bad debts written off (償却債権取立益)"
    )
  , ( MiscellaneousIncome
    , "Miscellaneous income"
    , "雑益"
    , "Revenue: Miscellaneous income (雑益)"
    )
  , ( ReversalOfAllowanceForDoubtfulAccounts
    , "Reversal of allowance for doubtful accounts"
    , "貸倒引当金戻入"
    , "Revenue: Reversal of allowance for doubtful accounts (貸倒引当金戻入). Credit counterpart used by the 差額補充法/洗替法 when the estimated allowance is smaller than the existing balance (the excess of 'AllowanceForDoubtfulAccounts' is released)."
    )
  ]
