#!/usr/bin/env python3
"""Generate ExchangeAlgebra.Assist.Descriptions from AccountTitles Haddock."""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ELEMENT_PATH = ROOT / "src" / "ExchangeAlgebra" / "Algebra" / "Base" / "Element.hs"
OUT_PATH = ROOT / "src" / "ExchangeAlgebra" / "Assist" / "Descriptions.hs"

CONSTRUCTOR_RE = re.compile(
    r"^\s*(?:data\s+AccountTitles\s*=|\|)\s*([A-Z][A-Za-z0-9_']*)\b(?:.*?--\s*\^\s*(.*))?$"
)
DIVISION_RE = re.compile(r"^[A-Za-z]+:\s*")


def has_non_ascii(text: str) -> bool:
    return any(ord(ch) > 127 for ch in text)


def split_description(desc: str) -> tuple[str, str, str] | None:
    if not DIVISION_RE.match(desc):
        return None

    body = DIVISION_RE.sub("", desc, count=1)
    for i, ch in enumerate(body):
        if ch != "(":
            continue
        end = body.find(")", i + 1)
        if end < 0:
            continue
        inside = body[i + 1 : end]
        if has_non_ascii(inside):
            name_en = body[:i].strip()
            name_ja = inside.strip()
            if name_en and name_ja:
                return name_en, name_ja, desc
    return None


def parse_account_descriptions(text: str) -> list[tuple[str, str, str, str]]:
    rows: list[tuple[str, str, str, str]] = []
    in_account_titles = False
    current: tuple[str, list[str], int] | None = None

    def finish_current() -> None:
        nonlocal current
        if current is None:
            return
        constructor, parts, _comment_col = current
        desc = " ".join(part.strip() for part in parts if part.strip())
        desc = " ".join(desc.split())
        parsed = split_description(desc)
        if parsed is not None:
            name_en, name_ja, desc_full = parsed
            rows.append((constructor, name_en, name_ja, desc_full))
        current = None

    for line in text.splitlines():
        if "data  AccountTitles" in line or "data AccountTitles" in line:
            in_account_titles = True

        if not in_account_titles:
            continue

        if "deriving" in line:
            finish_current()
            break

        match = CONSTRUCTOR_RE.match(line)
        if match is not None:
            finish_current()
            constructor = match.group(1)
            comment = match.group(2) or ""
            marker = line.find("-- ^")
            comment_col = marker if marker >= 0 else len(line)
            current = (constructor, [comment], comment_col)
            continue

        if current is None:
            continue

        stripped = line.lstrip()
        indent = len(line) - len(stripped)
        constructor, parts, comment_col = current
        if stripped.startswith("--") and indent >= comment_col:
            continuation = stripped[2:].strip()
            if continuation.startswith("^"):
                continuation = continuation[1:].strip()
            current = (constructor, parts + [continuation], comment_col)

    return rows


def hs_string(text: str) -> str:
    escaped = (
        text.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def render(rows: list[tuple[str, str, str, str]]) -> str:
    rendered_rows = []
    for constructor, name_en, name_ja, desc in rows:
        rendered_rows.append(
            f"( {constructor}\n"
            f"    , {hs_string(name_en)}\n"
            f"    , {hs_string(name_ja)}\n"
            f"    , {hs_string(desc)}\n"
            f"    )"
        )

    body = "    " + "\n  , ".join(rendered_rows)
    return (
        "{-# LANGUAGE OverloadedStrings #-}\n"
        "{-# OPTIONS_GHC -Wno-deprecations #-}\n"
        "\n"
        "-- GENERATED by tools/gen-assist-descriptions.py — do not edit\n"
        "\n"
        "module ExchangeAlgebra.Assist.Descriptions\n"
        "    ( accountDescriptions\n"
        "    ) where\n"
        "\n"
        "import Data.Text (Text)\n"
        "\n"
        "import ExchangeAlgebra.Algebra.Base (AccountTitles(..))\n"
        "\n"
        "accountDescriptions :: [(AccountTitles, Text, Text, Text)]\n"
        f"accountDescriptions =\n  [\n{body}\n  ]\n"
    )


def main() -> None:
    rows = parse_account_descriptions(ELEMENT_PATH.read_text(encoding="utf-8"))
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(render(rows), encoding="utf-8")
    print(f"wrote {OUT_PATH} ({len(rows)} descriptions)")


if __name__ == "__main__":
    main()
