#!/usr/bin/env python3
"""Generate the JCCI 2022 alias overlay module from the frozen query fixture."""

from __future__ import annotations

import argparse
import csv
import json
from collections import defaultdict
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "fixture",
        nargs="?",
        type=Path,
        default=Path("test/fixtures/jcci-2022/queries.tsv"),
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    aliases: dict[str, list[str]] = defaultdict(list)
    with args.fixture.open(encoding="utf-8", newline="") as handle:
        for row in csv.DictReader(handle, delimiter="\t"):
            for constructor in row["candidates"].split("|"):
                if row["query"] not in aliases[constructor]:
                    aliases[constructor].append(row["query"])

    print("{-# LANGUAGE OverloadedStrings #-}")
    print("{-# OPTIONS_GHC -Wno-deprecations #-}")
    print()
    print("-- Generated by tools/gen-jcci-aliases.py. Do not edit by hand.")
    print("module ExchangeAlgebra.Algebra.Base.Account.JcciAliases")
    print("    ( jcciAliases ) where")
    print()
    print("import Data.Text (Text)")
    print("import ExchangeAlgebra.Algebra.Base.Element (AccountTitles(..))")
    print()
    print("jcciAliases :: AccountTitles -> [Text]")
    for constructor in sorted(aliases):
        rendered = ", ".join(json.dumps(alias, ensure_ascii=False) for alias in aliases[constructor])
        print(f"jcciAliases {constructor} = [{rendered}]")
    print("jcciAliases _ = []")


if __name__ == "__main__":
    main()
